### ISSUE TITLE
SVG tag

### ISSUE THREAD

**Issue by brussee** [0x00000001A/es6-string-html#27]
@mydesireiscoma Could you please make it possible to write `/*svg*/` instead of `/*html*/` to indicate being inside a `<svg>` tag and activate svg syntax highlighting (already part of the current html syntax highlighting, so hopefully not that difficult).

Intended use case:
```
myDiv.innerHTML = /*html*/`
<svg viewBox="0 0 100 100">
    ${myArray.reduce((html, elmnt) => html + /*svg*/`<text x="0" y="0">${elmnt.txt}</text>`, '')}
</svg>
```

**Comment by 0x00000001A** [comment]
New version of the extension that contains the feature (svg support) has been uploaded just now

**Comment by brussee** [comment]
Thank you very much! I updated the VSCode plugin and this is how it looks for me (insiders build):

![es6-string-html](https://user-images.githubusercontent.com/738052/115906809-53896780-a468-11eb-936e-c1fbbfcaffac.PNG)

**Comment by 0x00000001A** [comment]
@brussee 
I'm sorry, but for now, I'm not found a way to solve this issue in a fast way.
Of course, I have some options, but they are a little bit heavy to implement, i.e. they will take some time to implement.

**Comment by brussee** [comment]
Thanks for your efforts! I'll keep watching this issue.
