### ISSUE TITLE
Syntax highlighting breaks with multiple placeholders in the same attribute

### ISSUE THREAD

**Issue by Zenoo** [0x00000001A/es6-string-html#28]
The highlighting works when you only have one placeholder in an attribute :
![Single placeholder](https://i.imgur.com/SUkhYLb.png)

But it breaks if there is more than one (the second `$` & the last `"` are not correctly colored):
![Multiple placeholders](https://i.imgur.com/AX2RMZ6.png)

**Comment by Zenoo** [comment]
I noticed another case where the highlighting breaks, it's apparently if there is anything after a `${...}` in an HTML attribute :
![Good](https://i.imgur.com/idQhguF.png)
![Bad](https://i.imgur.com/qdcf7fv.png)

**Comment by 0x00000001A** [comment]
Fixed version has been published just now
