### ISSUE TITLE
ignore required comment case and spaces

### ISSUE THREAD

**Issue by noelmace** [0x00000001A/es6-string-html#29]
**Motivation**

Some other tools require another case or spacing.

**Reproduction**

Prettier requires `/* HTML */`. When using it instead of `/*html*/`, syntax highlighting stop working.

See:
- https://prettier.io/blog/2018/11/07/1.15.0.html#html-template-literal-in-javascript
- https://github.com/prettier/prettier/issues/3548

**Comment by 0x00000001A** [comment]
Added flag, that should (according to textmate docs) should ignore casing
Optional flag for space already exists
Updated version has been published just now
