### ISSUE TITLE
Add Extension to Open VSX registry

### ISSUE THREAD

**Issue by HuM4NoiD** [0x00000001A/es6-string-html#36]
Can you also add this extension to [open vsx registry](https://open-vsx.org/)?

**Comment by 0x00000001A** [comment]
Sure
Sry for late reply

**Comment by 0x00000001A** [comment]
@HuM4NoiD 
The extension was published
https://open-vsx.org/extension/Tobermory/es6-string-html

Namespace claim was requested here
https://github.com/EclipseFdn/open-vsx.org/issues/468

**Comment by HuM4NoiD** [comment]
Thank you!
