### ISSUE TITLE
sql tagged templates mess up all the following syntax highlighting

### ISSUE THREAD

**Issue by CherryDT** [0x00000001A/es6-string-html#47]
Issue Type: <b>Bug</b>

Put this code into a JavaScript file:

```javascript
const abc = await db.query(sql`SELECT 1`)
if (!dbLine) {
  console.warn(`Blah`)
}

const foobar = await xyz()
```

You will see this messed-up syntax highlighting below the first line:

![image](https://user-images.githubusercontent.com/6010463/170709053-764df5e7-6af8-48d9-b16a-d57c1d1b761b.png)

When disabling your extension, it looks OK:

![image](https://user-images.githubusercontent.com/6010463/170709090-532b9d91-973b-4034-ad64-77b9f25fea9c.png)

---

Extension version: 2.12.0
VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:15:52.058Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 4.4.0-19041-Microsoft
Remote OS version: Linux x64 4.4.0-19041-Microsoft
Connection to 'wsl+Ubuntu-20.04' could not be established

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 PRO 4750U with Radeon Graphics (16 x 1697)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.23GB (9.56GB free)|
|Process Argv|--crash-reporter-id 86814b6d-9362-4292-9bc7-43662930765a|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 4.4.0-19041-Microsoft|
|CPUs|AMD Ryzen 7 PRO 4750U with Radeon Graphics (16 x 1700)|
|Memory (System)|31.23GB (9.63GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 4.4.0-19041-Microsoft|
|CPUs|AMD Ryzen 7 PRO 4750U with Radeon Graphics (16 x 1700)|
|Memory (System)|31.23GB (9.63GB free)|
|VM|0%|

Connection to 'wsl+Ubuntu-20.04' could not be established
</details>

**Comment by zadeviggers** [comment]
I've had a similar issue with this extension breaking syntax highlighting. I've only noticed it occurring when using TypeScript generics, and the `sql` function call is wrapped in parentheses (e.g. to await the function then access a property on it).
<img width="461" alt="image" src="https://github.com/0x00000001A/es6-string-html/assets/74938858/994529ef-7f7a-40f4-a769-30e8927786de">

**Comment by jdukleth** [comment]
I have this issue too when using Prisma. It butchers the syntax highlighting in the entire file (below the line).

![image](https://github.com/0x00000001A/es6-string-html/assets/15095818/fe726d40-cdd3-4758-b031-f3aad89ebbbe)

**Comment by jdukleth** [comment]
I have put in a [pull request](https://github.com/0x00000001A/es6-string-html/pull/56) that fixes the original post and also my case of using ORMs like Prisma that have "<variableName>.sql" syntaxes.

I couldn't figure out the TypeScript one. You might want to open a separate issue for that as that is a much more complex fix.
